Feature/ac 10 create user signup login flow
A-Comosus/comosus-client pull request #55
Opened 2022-06-01 02:01 UTC by turnkevin

Create signup page and do the localisation.

2022-06-02 11:32 UTC, NorrisWu0 commented on .vscode/settings.json
> +  "jira-plugin.workingProject": ""
What is this?

2022-06-02 11:43 UTC, NorrisWu0 requested changes

2022-06-02 11:43 UTC, NorrisWu0 commented on .env.development
> +NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://a-comosus.com:3100/graphql/
I don't think we need to commit this, but it can stay here for now.

2022-06-02 11:43 UTC, NorrisWu0 commented on public/locales/cn/auth.json
> +    "error": "要嘛不是用户名不对，就是密码不对。",
I don't think you need this error here.

2022-06-02 11:43 UTC, NorrisWu0 commented on public/locales/cn/auth.json
> +    "user-exist": "用户已存在，请换用户名。",
Imagine our backend will return different errors. We can group this type of message under `error` object.

```
{
  error: {
    existing-user.
    ...other rule,
  }
}

2022-06-02 11:43 UTC, NorrisWu0 commented on public/locales/cn/auth.json
> +      "title": "创建帐户即表示您同意我们的条款和条件。查看我们的隐私声明，了解我们如何管理您的个人信息。",
u sure this is `title`?

2022-06-02 11:43 UTC, NorrisWu0 commented on src/common/components/generics/Policy.tsx
> +export default function Policy({ name, control }) {
So there are two different scenarios here.

if we are reusing this component else where, should it really be called `Policy`?

If we are not reusing it, then should it be a component under `@common` or does it belongs to its respective module?

2022-06-02 11:43 UTC, NorrisWu0 commented on src/common/components/index.ts
> +export { default as Policy } from './generics/Policy';
Same as above

2022-06-02 11:43 UTC, NorrisWu0 commented on src/modules/auth/LoginForm/login.gql
> +mutation Register($payload: RegisterDetailInput!) {
You can either rename this file to `auth.gql` or create a separate `signup.gql`

2022-06-02 11:43 UTC, NorrisWu0 commented on src/styles/Home.module.css
> +
?

2022-06-04 01:20 UTC, turnkevin commented on .vscode/settings.json
> +  "jira-plugin.workingProject": ""
I have already cancelled it.

2022-06-04 10:41 UTC, NorrisWu0 approved these changes

2022-06-04 10:51 UTC, merged