[AC-xx: CI-CD] Kelvin - add Jenkinsfile, Dockerfile and eks yaml.
A-Comosus/comosus-client pull request #80
Opened 2022-07-11 13:26 UTC by NubKel

### Provide descriptions of this pull request.
Add Dockerfile, eks yaml file for future deployment purposes, Jenkinsfile with a pipeline including code checks, backup image to ECR and deploy frontend service in ECS.

### Provide screenshots of no warning, error in console.
![image](https://user-images.githubusercontent.com/39546456/178272402-06220cfd-5858-4101-9c3f-2d363dc5d171.png)
The pipeline works as expected.

![image](https://user-images.githubusercontent.com/39546456/178272808-079b53dc-023f-4270-ab40-31460a223c36.png)
The docker image uploads to ECR.

![image](https://user-images.githubusercontent.com/39546456/178273228-5db171e3-1e81-4068-982c-33296ea43c50.png)
The service deploys to ECS.

- [x] No merge conflict with the `develop` branch.
- [x] Check PR title is correct, (i.e `[AC-xx: Feature] Create pull request template`).
- [x] Check your app will run without crashes.
- [x] Check if there are hard coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] No unnecessary spaces between lines of code.
- [ ] Check you are using `camelCase && PascalCase` correctly.
- [x] Check you named your code properly.
- [ ] Remove unused comments.

2022-07-12 10:28 UTC, tardigrade425 requested changes

2022-07-12 10:28 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Kelvin
> +        // stage ('Deploying to EKS...') {
注释去掉

2022-07-12 10:28 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Kelvin
> +                    branch 'ci-cd/*'
改成精确触发你的branch

2022-07-12 10:28 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Kelvin
> +    }
加上 Post

2022-07-12 10:28 UTC, tardigrade425 commented on Dockerfile.Kelvin
> +# If using npm with a `package-lock.json` comment out above and use below instead
没用的注释去了

2022-07-12 12:59 UTC, NubKel commented on CI-CD/Jenkinsfile.Kelvin
> +                    branch 'ci-cd/*'
這個可以保留develop吧? CICD的branch先刪除? 因為這個branch一旦merge之後specify當前的branch也沒意義了

2022-07-12 12:59 UTC, NubKel commented on CI-CD/Jenkinsfile.Kelvin
> +        // stage ('Deploying to EKS...') {
Done

2022-07-12 12:59 UTC, NubKel commented on CI-CD/Jenkinsfile.Kelvin
> +    }
Done

2022-07-12 12:59 UTC, NubKel commented on Dockerfile.Kelvin
> +# If using npm with a `package-lock.json` comment out above and use below instead
Done

2022-07-14 08:48 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Kelvin
> +                    branch 'ci-cd/*'
如果有其他ci-cd开头的branch，会把其他人的也build

2022-07-14 08:49 UTC, tardigrade425 approved these changes

2022-07-14 10:17 UTC, merged