[AC-105: Feature] Create a homepage
A-Comosus/comosus-client pull request #85
Opened 2022-07-15 07:33 UTC by miaozhaod

### Provide screenshots or videos that the function is working.
https://user-images.githubusercontent.com/89491470/179170927-958c7b57-03d5-4cb6-90e7-ad63a32d121d.mov

### Provide screenshots of no warning, error in console.
I keep getting this warning, but after google, I'm still not sure how to resolve it 😩
<img width="184" alt="Screen Shot 2022-07-15 at 5 30 35 pm" src="https://user-images.githubusercontent.com/89491470/179174531-2f0ac574-b8f1-4455-be3e-370d0d2b0602.png">

- [x] No merge conflict with the `develop` branch.
- [x] Check PR title is correct, (i.e `[AC-xx: Feature] Create pull request template`).
- [x] Check your app will run without crashes.
- [x] Check if there are hard coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] No unnecessary spaces between lines of code.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Check you named your code properly.
- [x] Remove unused comments.

2022-07-16 03:59 UTC, NorrisWu0 commented
Hang on, does the design match?

2022-07-16 13:21 UTC, NorrisWu0 requested changes

2022-07-16 13:21 UTC, NorrisWu0 commented on public/locales/cn/homepage.json
> +{
Maybe rename this file to `home.json`

2022-07-16 13:21 UTC, NorrisWu0 commented on public/locales/cn/navbar.json
> +{
Think we can move this to `common.json`

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/Hero.tsx
> +import React from 'react';
Maybe make this a container as well

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/Hero.tsx
> +      className="heroContainer"
Hmmmmmm

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/Hero.tsx
> +        <Text type="h1" color="#F0F435">
I think we can make line 38 - line 48 the `children` of `HeroContainer/HeroLayout`

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/Logo.tsx
> +        src="/assets/a-comosus-logo.png"
Remember to remove `a-comosus-logo.svg` if we not using it anymore.

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/NavBar.tsx
> +  const authItems = [
Since there's only login and sign up, we can just code with the value directly, instead of passing props via this object array

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/NavBar.tsx
> +      href: '/login',
Routes need to be fetched via constants

2022-07-16 13:21 UTC, NorrisWu0 commented on src/common/components/generics/NavBar.tsx
> +        <Link href="/">
constant here as well

2022-07-16 13:21 UTC, NorrisWu0 commented on src/pages/index.tsx
> +              flexDirection={hero.flexDirection}
instead of having another field for `flex-direction`, I think having even/odd number to decide this would be better

2022-07-17 00:03 UTC, miaozhaod commented on public/locales/cn/homepage.json
> +{
updated

2022-07-17 00:08 UTC, miaozhaod commented on src/common/components/generics/Hero.tsx
> +      className="heroContainer"
removed ><

2022-07-17 04:35 UTC, miaozhaod commented on public/locales/cn/navbar.json
> +{
Moved

2022-07-17 04:36 UTC, miaozhaod commented on src/common/components/generics/Hero.tsx
> +import React from 'react';
Created a generic component `SectionContainer`

2022-07-17 04:38 UTC, miaozhaod commented on src/common/components/generics/Hero.tsx
> +        <Text type="h1" color="#F0F435">
Created a `SectionWrapper` to handle the flex-direction and width, and the `Hero` component is purely used to render content.

2022-07-17 04:38 UTC, miaozhaod commented on src/common/components/generics/Logo.tsx
> +        src="/assets/a-comosus-logo.png"
Deleted

2022-07-17 04:39 UTC, miaozhaod commented on src/common/components/generics/NavBar.tsx
> +  const authItems = [
Updated by directly putting into code

2022-07-17 04:39 UTC, miaozhaod commented on src/common/components/generics/NavBar.tsx
> +      href: '/login',
Updated

2022-07-17 04:39 UTC, miaozhaod commented on src/common/components/generics/NavBar.tsx
> +        <Link href="/">
yah, updated as well

2022-07-17 04:40 UTC, miaozhaod commented on src/pages/index.tsx
> +              flexDirection={hero.flexDirection}
As above, "Created a SectionWrapper to handle the flex-direction and width, and the Hero component is purely used to render content."

2022-07-17 10:39 UTC, NorrisWu0 approved these changes

2022-07-17 10:51 UTC, merged